### ISSUE TITLE
Aonde inserir o email e o token do sandbox?

### ISSUE THREAD

**Issue by diegoestacho999** [bergergit/ionic-pagseguro#3]
Amigo, eu criei o servidor e estou utilizando o seu código aqui. Porém não achei nenhum lugar para informar o email e o token do sandbox, em que trecho do código posso fazer isso?

Meu console retorna isso : 

`GET http://localhost:8100/null 404 (Not Found)`
`POST https://sandbox.pagseguro.uol.com.br/rb_bf36420ooi 403`
`Erro ao iniciar sessao Response {_body: "<!DOCTYPE html>↵<html lang="en">↵<head>↵<meta char…ody>↵<pre>Cannot GET /null</pre>↵</body>↵</html>↵", status: 404, ok: false, statusText: "Not Found", headers: Headers, …}`

**Comment by bergergit** [comment]
Fala @diegoestacho999.
O inicio da sessão deve ser feito por um servidor, e não pelo Ionic.
Na documentação eu dei um exemplo de como fazer isso usando Node.js e Firebase Functions.
Se você nao conhece Firabse Functions, da uma olhada na documentação deles aqui: https://firebase.google.com/docs/functions/

Abraços.

**Comment by diegoestacho999** [comment]
Opa tudo bem? Desculpe o incômodo novamente, mas deixa eu tirar uma dúvida.
Em relação a inicialização do servidor eu consigo fazer agora, estou com alguns problemas de CORS, mas estou contornando a situação.
A minha dúvida é, aonde eu insiro as credenciais do meu cliente, no caso os dados da conta do pagseguro, como e-mail e token?
Eu devo fazer a inserção desses dados aonde exatamente? Você consegue me dar uma ajuda nessa parte?

Abraços

**Comment by bergergit** [comment]
@diegoestacho999 da uma olhada no exemplo na documentaçao:
```
request.post({
   url: functions.config().pagseguro.session_url, 
   qs: { email: functions.config().pagseguro.email, token: functions.config().pagseguro.token }
}, 
```
Estou pegando esses valores usando functions.config()

Você define esses parametros usando configurações de ambiente nas suas functions
Dê uma lida nessa documentaçao: https://firebase.google.com/docs/functions/config-env

Abraços.

**Comment by diegoestacho999** [comment]
Opa, maravilha a princípio estou quase lá, agradecido pelas respostas anteriores e pelo suporte até agora.

Tire-me uma dúvida por gentileza, qual a url que você passa por parâmetro em pagseguro.session_url ?

Estou recebendo o seguinte em meu console, e acredito eu que não está iniciando a sessão por alguma informação incorreta.

`main.js:150 Erro ao iniciar sessao TypeError: Cannot read property 'id' of undefined
    at main.js:140
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:5085)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:5076)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)`

Recebo isso também:

`headers: Headers {_headers: Map(4), _normalizedNames: Map(4)}
ok: true
status: 200
statusText: "OK"
type: 2
url: "http://localhost/null"
_body: "<!DOCTYPE html>↵<html lang="en" dir="ltr">↵<head>↵  <script data-ionic="inject">↵    (function(w){var i=w.Ionic=w.Ionic||{};i.version='3.9.3';i.angular='5.2.11';i.staticDir='build/';})(window);↵  </script>↵  <meta charset="UTF-8">↵  <title>Ionic App</title>↵  <meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">↵  <meta name="format-detection" content="telephone=no">↵  <meta name="msapplication-tap-highlight" content="no">↵↵  <link rel="icon" type="image/x-icon" href="assets/icon/favicon.ico">↵  <link rel="manifest" href="manifest.json">↵  <meta name="theme-color" content="#4e8ef7">↵↵  ↵  <meta name="apple-mobile-web-app-capable" content="yes">↵  <meta name="apple-mobile-web-app-status-bar-style" content="black">↵↵  ↵  <script src="cordova.js"></script>↵↵  ↵↵  <link href="build/main.css" rel="stylesheet">↵↵</head>↵<body>↵↵  ↵  <ion-app></ion-app>↵↵  ↵  <script src="build/polyfills.js"></script>↵↵  ↵  <script src="build/vendor.js"></script>↵↵  ↵  <script src="build/main.js"></script>↵↵</body>↵</html>↵"
__proto__: Body`


A minha function está escrita dessa forma:
Acredito que o erro acima, esteja caindo na linha 15 dessa function.

`const functions = require('firebase-functions');
const cors = require('cors');

exports.startSession = functions.https.onRequest((req, res) => {
  
  // Enable CORS using the `cors` express middleware.
  cors(req, res, () => {
      res.header("Access-Control-Allow-Origin", "*");
      request.post({
          url: functions.config().pagseguro.session_url,
          qs: { email: functions.config().pagseguro.email, token: functions.config().pagseguro.token }
      }, function result(err, httpResponse, body) {
          if (err || httpResponse.statusCode !== 200) {
              console.error('Start session error', err);
              console.error('body', body);
              res.status(httpResponse && httpResponse.statusCode || 500).send();
              return;
          }
          res.status(200).send(parser.toJson(body));
          console.log('este é o body caso o status seja 200: ' +body)
      });
  });
});`

E por fim, o meu response retorna 200 ao tentar a conexão:

`Response
headers: Headers {_headers: Map(4), _normalizedNames: Map(4)}
ok: true
status: 200
statusText: "OK"
type: 2
url: "http://localhost/null"
_body: "<!DOCTYPE html>↵<html lang="en" dir="ltr">↵<head>↵  <script data-ionic="inject">↵    (function(w){var i=w.Ionic=w.Ionic||{};i.version='3.9.3';i.angular='5.2.11';i.staticDir='build/';})(window);↵  </script>↵  <meta charset="UTF-8">↵  <title>Ionic App</title>↵  <meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">↵  <meta name="format-detection" content="telephone=no">↵  <meta name="msapplication-tap-highlight" content="no">↵↵  <link rel="icon" type="image/x-icon" href="assets/icon/favicon.ico">↵  <link rel="manifest" href="manifest.json">↵  <meta name="theme-color" content="#4e8ef7">↵↵  ↵  <meta name="apple-mobile-web-app-capable" content="yes">↵  <meta name="apple-mobile-web-app-status-bar-style" content="black">↵↵  ↵  <script src="cordova.js"></script>↵↵  ↵↵  <link href="build/main.css" rel="stylesheet">↵↵</head>↵<body>↵↵  ↵  <ion-app></ion-app>↵↵  ↵  <script src="build/polyfills.js"></script>↵↵  ↵  <script src="build/vendor.js"></script>↵↵  ↵  <script src="build/main.js"></script>↵↵</body>↵</html>↵"
__proto__: Body`

Qualquer ajuda será bem vinda, e mais uma vez obrigado pelas respostas anteriores.

**Comment by bergergit** [comment]
@diegoestacho999 a session_url é um parametro que eu defini na function usando configurações de ambiente da function, conforme link que passei acima.

Essa URL é a de inicio de sessao do checkout transparente. Está bem explicado na documentação deles: https://dev.pagseguro.uol.com.br/v2/reference#api-checkout-transparente-iniciando-uma-sessao-de-pagamento

O "erro" que você está vendo aí, é apenas um HTML inteiro. Acho que está precisando de mais fundamentos.
Dê uma boa lida na documentação do Firebase sobre como invocar functions a partir do Ionic.
O Josh Morony tambem tem excelentes tutoriais sobre Ionic e integrações com Firebase: https://www.joshmorony.com/topics/ionic-tutorials/

(fechando o tópico pois o problema em questão não está relacionado com a biblioteca)
