### ISSUE TITLE
SSL duvida?

### ISSUE THREAD

**Issue by megadrazz** [bergergit/ionic-pagseguro#4]
como e feita o CHECKOUT sem ssl? porque a partir de junho de 2018 o pagseguro exigir ssl!!!

**Comment by bergergit** [comment]
@megadrazz você deve servir seu site via https sim. Sua API deve iniciar sessao via https tambem com a API do PagSeguro (exemplo: https://ws.pagseguro.uol.com.br/v2/sessions) e seu cliente deve se comunicar com sua API via https para fazer o checkout transparente.

Dá uma estudada no material de checkout transparente do UOL: https://dev.pagseguro.uol.com.br/v2/reference#api-checkout-transparente-iniciando-uma-sessao-de-pagamento
